version: '3.8'
services:
  AngularPet:
    container_name: AngularPet
    image: acarli/team_2_angularpet
    build: ./AngularPet
    ports:
    - target: 8080
      published: 8080

  Java-Pet:
    container_name: JavaPet
    image: acarli/team_2_javapet
    build: ./JavaPet
    ports:
    - target: 9966
      published: 9966

  NGINX:
    container_name: NGINX
    image: acarli/nginx:latest
    ports:
    - target: 80 
      published: 80 
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf